"""empty message

Revision ID: 79b587db6a00
Revises: 
Create Date: 2023-03-28 17:32:25.433535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79b587db6a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wardrobe')
    op.drop_table('beds')
    op.drop_table('couches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couches',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_type', mysql.SET('Canto', 'Sofá-cama', 'Poltrona', 'Retrátil'), nullable=True),
    sa.Column('product_size', mysql.SET('2 lugares', '3 lugares', '4 lugares'), nullable=True),
    sa.Column('amount_stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('beds',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_type', mysql.SET('Cama box', 'Bicama', 'Tradicional de Madeira', 'Cama baú'), nullable=True),
    sa.Column('product_size', mysql.SET('Solteiro', 'Casal'), nullable=True),
    sa.Column('amount_stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wardrobe',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_type', mysql.SET('Porta de correr sem espelho', 'Porta de puxar sem espelho', 'Porta de correr e espelho', 'Porta de puxar e espelho'), nullable=True),
    sa.Column('product_size', mysql.SET('2 portas', '3 portas', '4 portas'), nullable=True),
    sa.Column('amount_stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
