"""empty message

Revision ID: 9d97ba7497f9
Revises: 82d26d1fd577
Create Date: 2023-03-29 21:12:17.108106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d97ba7497f9'
down_revision = '82d26d1fd577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('is_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beds', 'is_good')
    # ### end Alembic commands ###
